[package]
name = "rustlings"
version = "0.1.0"
authors = ["Carol (Nichols || Goulding) <carol.nichols@gmail.com>"]

[dependencies]
handlebars = "2.0.2"
serde_json = "1.0.10"
prlink = { git = "https://github.com/btbytes/prlink" }
